### ISSUE TITLE
Update package layout to PyAnsys guidelines

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/pydpf-core#296]
As with other projects in the PyAnsys ecosystem, the layout of this project should adapt to the general guidelines.

## Low effort

- [ ] Enable Ruff rules
  - [ ] PyCodestyle
  - [x] PyDocstyle, see https://github.com/ansys/pydpf-core/pull/1975
  - [ ] PyFlakes, see https://github.com/ansys/pydpf-core/pull/1953
  - [x] Isort, see #2021 
  - [ ] PEP8-Naming
  - [x] Flake8-use-pathlib, see https://github.com/ansys/pydpf-core/pull/1949
  - [x] Flake8-todos, see https://github.com/ansys/pydpf-core/pull/1981

- [ ] Remove autoapi warning suppression once the codebase is healthier. See #1967 
- [x] Address removed reference labels from module docstrings. See #1980 

## Intermediate effort

- [x] Use a `src/` layout. Just need to move the "ansys/" dir inside a "src/" one and fix some links to this new location: #664

- [x] Use a `pyproject.toml` and drop any `setup.py` or `setup.cfg` files. https://github.com/ansys/pydpf-core/pull/909

- [x] Rename ``/docs`` directory to ``/doc``: Link issue here.

- [x] Implement Tox for the project
  - [x] Drop any patch scripts in favor of Tox 
    - #1989 
    - #2015 
    - #2031
    - #2056

- [x] Use sphinx-autoapi for generating the API reference, see https://github.com/ansys/pydpf-core/pull/1952
- [x] Improve static search live preview performance and fix missing module icons in the api documentation, see #1971 

## High effort

- [ ] Use containers from the GitHub Container Registry in the CI/CD
- [ ] Use semver tags

More about packaging guidelines in https://dev.docs.pyansys.com/packaging/structure.html.

**Comment by jorgepiloto** [comment]
@pyansys-automation never close issue

**Comment by jorgepiloto** [comment]
This issue is a meta-issue. Efforts for implementing and fixing its child issues have been made over the last years. Thus, we'll close it once all the minor issues have been fixed.
